### ISSUE TITLE
**User Story: Poster_Text_Idea**

### ISSUE THREAD

**Issue by LukasInf17** [stuttgart-dhbw/com.dhbw.team3#56]
**Story Points:** 2 SP

The poster should have some text and graphics about the project so we need some ideas which "facts" are important.

**Comment by LukasSchn** [comment]
#53 Poster layout suggestion
draft for layout.
[Posterlayout Vorschlag.pdf](https://github.com/stuttgart-dhbw/com.dhbw.team3/files/2518439/Posterlayout.Vorschlag.pdf)
